import './globals.css'
export const metadata = {
  title: 'Full stack App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <head/>
      <body className="">
        {children}
      </body>
    </html>
  )
}
