import '../globals.css'
import { Inter } from 'next/font/google'
import { Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: '--font-montserrat'
})

export const metadata = {
  title: 'Movie Details',
  description: 'Generated by create next app',
}

export default function MovieLayout({ children }) {
  return (
      <section className='movie-page'>
        {children}
      </section>
  )
}
